apiVersion: app.ibm.com/v1alpha1
kind: KubevirtAddon
metadata:
  name: guestbook-application
spec:
  generate: 
    services:
    - metadata:
        name: redis-master
        namespace: default
        labels:
          app: redis
          role: master
          tier: backend
      vmi:
        name: redis-master
        namespace: default
      port: 6379
      targetPort: 6379
    - metadata:
        name: 
        
