apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtaddons.app.ibm.com
spec:
  group: app.ibm.com
  names:
    kind: KubevirtAddon
    listKind: KubevirtAddonList
    plural: kubevirtaddons
    singular: kubevirtaddon
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KubevirtAddon is the Schema for the kubevirtaddons API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KubevirtAddonSpec defines the desired state of KubevirtAddon
          properties:
            generate:
              description: GenerateSpec defines the gvr and wanted metadata to be
                used for generating new objects
              properties:
                routes:
                  items:
                    description: RouteSpec defines the details of the routes to be
                      generated
                    properties:
                      host:
                        type: string
                      metadata:
                        type: object
                    type: object
                  type: array
                services:
                  items:
                    description: ServiceSpec defines the details of the service to
                      be generated
                    properties:
                      generateEndpoint:
                        type: boolean
                      host:
                        type: string
                      metadata:
                        type: object
                      port:
                        format: int32
                        type: integer
                      selector:
                        additionalProperties:
                          type: string
                        type: object
                      targetPort:
                        format: int32
                        type: integer
                      vmi:
                        description: VMISpec defines which resource is targeted for
                          generation
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        required:
                        - name
                        - namespace
                        type: object
                    type: object
                  type: array
              type: object
          type: object
        status:
          description: KubevirtAddonStatus defines the observed state of KubevirtAddon
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
