apiVersion: app.ibm.com/v1alpha1
kind: KubevirtAddon
metadata:
  name: guestbook-application
spec:
  generate: 
    services:
    - name: redis-master
      namespace: default
      labels:
        app: redis
        role: master
        tier: backend
      port: 6379
      targetPort: 6379
    - name: redis-slave
      namespace: default
      labels:
        app: redis
        role: slave
        tier: backend
      port: 6379
    - name: frontend
      namespace: default
      labels:
        app: guestbook
        tier: frontend
      port: 31323
      targetPort: 80
      host: guestbook.apps.folie.os.fyre.ibm.com
      generateEndpoint: true
        
