kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-addon
subjects:
- kind: ServiceAccount
  name: kubevirt-addon
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubevirt-addon
  apiGroup: rbac.authorization.k8s.io