apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-addon
  template:
    metadata:
      labels:
        name: kubevirt-addon
    spec:
      serviceAccountName: kubevirt-addon
      containers:
        - name: kubevirt-addon
          # Replace this with the built image name
          image: quay.io/stevekimibm/kubevirt-addon
          command:
          - kubevirt-addon
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubevirt-addon"
