apiVersion: app.ibm.com/v1alpha1
kind: KubevirtAddon
metadata:
  name: frontend
spec:
  vmi:
    name: frontend
    namespace: default
  generate:
    services:
    - name: frontend
      namespace: default
      labels:
        app: guestbook
      port: 31323
      targetPort: 80
      selector:
        app: frontend
    routes:
    - serviceRef:
        name: frontend
        namespace: default
      host: guestbook.apps.folie.os.fyre.ibm.com
      generateEndpoint: true